# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static # ✅ Dynamic에서 Static으로 변경
end

target 'Cocktail_Front' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Google Maps 설정
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'GoogleMaps', '~> 8.4.0'
  pod 'Google-Maps-iOS-Utils', '5.0.0'
  pod 'react-native-google-maps', :path => rn_maps_path

  # ✅ RNKakaoLogins 모듈 추가 (필요 시)
  pod 'kakao-login', :path => '../node_modules/@react-native-seoul/kakao-login'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # ✅ 모든 모듈에 CLANG_ENABLE_MODULES 및 HEADER_SEARCH_PATHS 설정
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/Headers/Public']
        
        # ✅ Allow Non-modular Includes in Framework Modules 설정
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end

      # ✅ RNKakaoLogins 모듈의 설정 (필요 시)
      if target.name == 'kakao-login'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        end
      end

      # ✅ react-native-google-maps 모듈의 설정
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/Headers/Public']
        end
      end
    end
  end
end
